<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>LightVerificationServer</AssemblyName>
    <RootNamespace>LightVerificationServer</RootNamespace>
  </PropertyGroup>

</Project>
